version: '4'

services:
  angular-frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - golang-service
    networks:
      - app-network

  golang-service:
    build:
      context: ./golang-service
      dockerfile: Dockerfile
    container_name: golang-service
    ports:
      - "3080:3080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - BASE_URL=http://python-service:3081
    depends_on:
      - python-service
    networks:
      - app-network

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: python-service
    ports:
      - "3081:3081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge